- YappProject.xcodeproj/project.pbxproj
- YappProject.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- YappProject/AppCoordinatorView.swift
- YappProject/AppView.swift
- YappProject/MainCoordinatorView.swift
- YappProject/MainPageScreen.swift
- YappProject/ModalCore.swift
- YappProject/ModalView.swift
- YappProject/SecondCore.swift
- YappProject/SecondView.swift
- YappProject/ThirdView.swift
- YappProject/YappProjectApp.swift
- YappProject/YappProjectCore.swift
* 일반적인 방식으로 Navigation 3 depth 이상 전환이 정상동작하지 않는 케이스 테스트
- SecondView -> ThirdView Navigation 방식 화면전환 시, 정상 동작하지 않음 (해당 문제 해결방식 고려 필요, TCA Navigation beta, TCACoordinator 등... 뭐가 가장 좋을지..)
> ModalView 추가 및 모달 전환 용 View로 대체, ThirdView 용도를 Navigation 전환 테스트 용으로 변경

- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
- floating button을 제작하였습니다.
- CafeMap Core에 button action, State 연동 로직을 추가하였습니다.
close #48
> [Feat] #48 floating button 제작

- Projects/Coffice/Sources/App/Extensions/View+Extensions.swift
- Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
- Projects/Coffice/Sources/App/ViewModifier/RoundedCornerViewModifier.swift
> [UI] 카페 카드뷰 제작

- Projects/Coffice/Sources/App/Dependencies/SearchPlaceAPIClient.swift
- Projects/Coffice/Sources/App/Entities/SearchPlaceRequestValue.swift
- Projects/Network/Sources/DTOs/SearchPlaceRequestDTO.swift
- 업데이트된 requestDTO에 맞게 매장 검색 api 메서드 제작을 진행했습니다.
close #79
> [Feat] #79 매장 검색 api 연동

- Projects/Coffice/Sources/App/Extensions/UITextView+Extensions.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewOptionButtonsCore.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewTextView.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewWriteCore.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewWriteView.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/Review/KeyboardPresentationReadable.swift
- 리뷰작성화면의 텍스트뷰 영역 UI 및 이벤트를 구현했습니다.
- 리뷰작성화면 입력 글자 수에 따라 텍스트뷰 우하단에 입력 글자 수가 업데이트 됩니다.
- 텍스트뷰 입력 시에 올라오는 키보드 위에 텍스트뷰가 위치하도록 했습니다. (KeyboardPresentationReadable 활용)
- 텍스트뷰 입력 상태에 따라 placeholder가 나오도록 설정
- 최대 200글자까지만 텍스트 입력되도록 처리
- 리뷰 반영 전 / 후 화면
<div>
</div>
```
```
close #81
> Feature/#81 review write textview UI

- Projects/Coffice/Sources/App/Dependencies/SearchPlaceAPIClient.swift
- Projects/Coffice/Sources/App/Entities/Address.swift
- Projects/Coffice/Sources/App/Entities/Cafe.swift
- Projects/Coffice/Sources/App/Entities/CafeFilters.swift
- Projects/Coffice/Sources/App/Entities/CafeSearchResponse.swift
- Projects/Coffice/Sources/App/Entities/SearchPlaceRequestValue.swift
- Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeCellView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearchListCell.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearchView.swift
- Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
- Projects/Network/Sources/CoreNetwork.swift
- Projects/Network/Sources/DTOs/Requests/SearchPlaceRequestDTO.swift
- Projects/Network/Sources/DTOs/Responses/Coordinate+AddressDTO.swift
> [Feat] #77 infinite scroll 구현

- Projects/Coffice/Sources/App/Extensions/CofficeImages+Extensions.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailCore.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailHeaderView.swift
- 카페 상세, 상단 이미지가 여러개일 경우 페이징 가능하도록 수정
- 테스트용 이미지 리스트 추가 (실제 image url이 없는 경우 표출하도록 임시 설정)
```
```
close #121
> [UI] #121 카페 상세, 상단 이미지 페이징 뷰 개발

- Projects/Coffice/Sources/App/Dependencies/SearchPlaceAPIClient.swift
- Projects/Coffice/Sources/App/Entities/PlaceRequestValue.swift
- Projects/Coffice/Sources/App/Entities/SortDescriptor.swift
- Projects/Coffice/Sources/App/Entities/WayPoint.swift
- Projects/Network/Sources/DTOs/Requests/PlaceRequestDTO.swift
- Projects/Network/Sources/DTOs/Responses/WayPointDTO.swift
- 지역명만 가지고 카페를 불러올 `fetchPlaces` 메서드 제작
- 역이름의 일부를 통해 역 이름들을 불러올 `fetchWayPoints` 메서드 제작
close #124
> Feature/#124 waypoint+place api

- Projects/Coffice/Sources/App/Entities/CafeFilters.swift
- Projects/Coffice/Sources/App/Entities/SearchPlaceRequestValue.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetViewState.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterInformation.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Network/Sources/DTOs/Requests/SearchPlaceRequestDTO.swift
- 카페 키워드 검색 시에 저장된 필터 설정을 적용하도록 하는 기능을 추가했습니다.
- 이번 기능을 적용하면, 다른 필터 적용 케이스에서도 동일한 방식으로 적용하고자 합니다.
- todo (cc: @NewHooon)
```
```
close #140
> [Feat] #140 (1/4) 카페 검색 시 필터 설정 적용

- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- 지도 마커 업데이트, 무한 스크롤 검색 시 필터 설정을 적용했습니다.
```
```
close #140
> [Feat] #140 (2~3/4) 지도 마커 업데이트, 무한 스크롤 검색 시 필터 설정 적용

- Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
카드 뷰 클릭 시, 상세화면 이동 기능을 추가하였습니다
close #
> [Feat] #129 cardView onTapGesture

- .swiftlint.yml
- Projects/Coffice/.swiftlint.yml
- Projects/Coffice/Sources/App/Dependencies/SearchPlaceAPIClient.swift
- Projects/Coffice/Sources/App/Entities/WayPoint.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearchView.swift
- Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
- Projects/Coffice/Sources/App/Main/Search/PlaceCellView.swift
- Projects/Coffice/Sources/App/Main/Search/WaypointCellView.swift
- 카페 검색 시, waypoint 및 place api 호출 구현
- 역기반 이동
// TODO: 연관검색어 Cell 클릭 시, 해당 장소로 이동
첨부해주세요.
close #133
> [Feat]/#133 카페 검색 시, waypoint 및 place api 호출 구현 및 역기반 이동

- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
- Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
카페 결과 리스트에서 cell 클릭 시, 해당 카페로 포커싱하는 기능을 구현하였습니다.
close #145
> [Feat] /#145 ListCellOnTapGesture

- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchView.swift
placeCell, waypointCell onTapGesture 를 추가하였습니다.
gif에서는 잘보이지 않지만, 각각의 셀을 클릭해서 해당 위치로 이동하는 동작입니다
close #150
> [Feat] #150 placeCell, waypointCell onTapGesture 추가

- Projects/Coffice/Sources/App/Entities/SearchPlaceRequestValue.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListCore.swift
- Projects/Coffice/Sources/App/Main/Search/NaverMap/NaverMapView.swift
필터 적용 시, 카페데이터 요청 및 지도에 반영
close #140
> [Feat]/#140 search place by filter

- Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheet.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterInformation.swift
cafeFilter 초기화 로직을 추가하였습니다.
close #168
> [Feat] #168 reset cafe filter

- Projects/Coffice/Sources/App/Extensions/String+Extensions.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearch/PlaceCellView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearch/WaypointCellView.swift
검색어 입력시, 연관검색어에 attributedString을 적용하였습니다.
close #163
> [Feat] #163 attributed string 적용

- Projects/Coffice/Sources/App/CommonComponents/CommonBottomSheet/BottomSheet.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewWriteCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewWriteView.swift
- 카페 상세, 리뷰 작성화면 뒤로가기 확인 팝업 UI 표출로직 추가
```
```
close #171
> [Feat] #171 카페 상세, 리뷰 작성화면 뒤로가기 확인 팝업 UI 표출로직 추가

- Projects/Coffice/Sources/App/CommonComponents/Toast/ToastView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailMenuView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailView.swift
- todo
```
```
close #139 
related #161 #170
> [Feat] #139 #161 리뷰 삭제 팝업 UI, 삭제 기능 추가

- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearch/SearchCoordinatorCore.swift
> [Chore] #165 검색 상세 버튼 제거

- Projects/Coffice/Sources/App/CommonComponents/CommonWebView.swift
- Projects/Coffice/Sources/App/Main/MyPage/AppServiceTerms/AppServiceTermsCore.swift
- Projects/Coffice/Sources/App/Main/MyPage/AppServiceTerms/AppServiceTermsView.swift
- Projects/Coffice/Sources/App/Main/MyPage/Coordinator+Screen/MyPageCoordinatorCore.swift
- Projects/Coffice/Sources/App/Main/MyPage/Coordinator+Screen/MyPageCoordinatorView.swift
- Projects/Coffice/Sources/App/Main/MyPage/Coordinator+Screen/MyPageScreenCore.swift
- Projects/Coffice/Sources/App/Main/MyPage/LocationServiceTerms/LocationServiceTermsCore.swift
- Projects/Coffice/Sources/App/Main/MyPage/LocationServiceTerms/LocationServiceTermsView.swift
- Projects/Coffice/Sources/App/Main/MyPage/MyPageCore.swift
- Projects/Coffice/Sources/App/Main/MyPage/PrivacyPolicy/PrivacyPolicyCore.swift
- Projects/Coffice/Sources/App/Main/MyPage/PrivacyPolicy/PrivacyPolicyView.swift
- 공용 웹뷰 추가 및 마이페이지 메뉴에 웹뷰를 추가했습니다. (서비스 이용약관, 위치 이용약관, 개인정보 처리방침)
- todo
- 카페 상세 등 타 화면의 웹뷰 연동은 따로 다른 카페 상세 작업 하면서 올리겠습니다.
```
```
close #175
> [Feat] #175 공용 웹뷰 추가 및 마이페이지 메뉴 웹뷰 연동

- Projects/Coffice/Sources/App/Entities/Cafe.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListCell.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListView.swift
- Projects/Coffice/Sources/App/Main/Search/NaverMap/NaverMapCore.swift
카페 검색결과리스트 셀 bookmark API 기능을 연동하였습니다.
TODO:
- mockData제거
close #188
> [Feat] #188 카페 검색결과리스트 셀 bookmark API 기능연동

- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
역 중심 카페 검색 시, 결과가 없다면  ToastView 표출되는 로직 추가
close #158
> [Feat] #158 검색결과 없을 시, ToastView 추가

- Projects/Coffice/Sources/App/Login/LoginView.swift
iOS15version에서 로그인 뷰 깨짐 현상을 수정하였습니다.
close #208
> [Fix] #208 iOS15version에서 로그인 뷰 깨짐 현상

- Projects/Coffice/Sources/App/AppCoordinatorCore.swift
- Projects/Coffice/Sources/App/AppCoordinatorView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterMenusCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterMenusView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearch/SearchScreenCore.swift
- 회원탈퇴, 로그아웃 후 로그인화면 복귀 시 Action 관련 에러 로그가 발생하는 문제를 수정했습니다.
자세한 내용은 아래 코드에 코멘트 달아두었어요~
- 로그아웃, 회원탈퇴 시에 정상적인 시점에 Effect action이 실행되지 않았다는 로그가 발생하지 않는지 확인
```
```
close #211
> [Bug] #211 회원탈퇴, 로그아웃 후 로그인화면 복귀 시 Action 관련 에러 로그 발생문제 수정

- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailMenuView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewOptionButtonsView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetViewState.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterMenusView.swift
[일부 둥근 테두리 버튼 UI가 디자인가이드와 맞지 않는 문제 수정](https://github.com/YAPP-Github/Coffice-iOS/commit/1482d81fa78b725df4d1addf9fd090672e8e92a4)
- 테두리가 inner stroke로 처리되지 않아서 UI가 잘리거나, 생각보다 얇아보이는 경우가 있어서 수정했습니다.
- 일부 테두리 색상이 사양과 달라서 수정했습니다.
수정 전/후
<div>
</div>
```
```
close #216
> [Fix] #216 일부 둥근 테두리 버튼 UI가 디자인가이드와 맞지 않는 문제 수정

- Projects/Coffice/Sources/App/Main/Search/NaverMap/NaverMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/NaverMap/NaverMapView.swift
기존 중복마커 검사로직을 위경도 검사로 설정했던 것을
placeId로 변경했습니다.
Double의 precision문제로 인해 버그가 발생한 것으로 보입니다.
close #225
> Fix/#225 중복마커 방지 로직 변경

- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailMenuView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailView.swift
- 카페 상세화면 url 정보를 통한 웹뷰 표출로직을 추가했습니다.
```
```
close #229
> [Feat] #229 카페 상세화면 url 정보를 통한 웹뷰 표출로직 추가

- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailHeaderView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailView.swift
- 카페상세 테스트용 이미지 제거
- placeholder 적용 및 공유버튼 임시 제거
<div>
</div>
```
```
related #186
> [Feat] #186 카페상세 테스트용 이미지 제거, placeholder 적용 및 공유버튼 임시 제거

- Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListCell.swift
- Projects/Coffice/Sources/App/Main/Search/CafeTagTextView.swift
CafeCardView,ListCell 빈 텍스트 UI가 보이는 현상을 수정하였습니다.
| <img src="https://github.com/YAPP-Github/Coffice-iOS/assets/108966759/de8272ea-53d2-4d93-8e5b-6eab8ad8f29f" width="200">  |  <img src="https://github.com/YAPP-Github/Coffice-iOS/assets/108966759/1440ef2f-01f1-46b5-bb19-338c9041f609" width="200"> |
close #228
> [Fix] #228 CafeCardView,ListCell 빈 텍스트 UI 수정

- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailSubInfoView.swift
CafeDetailView margin을 조정했습니다
width="200">
close #241
> [Chore] #241 CafeDetailView margin 조정

- Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
> [UI] #255 현위치 재검색 UI 수정

- Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewWriteView.swift
- 카페상세, 리뷰 작성 상단 UI 이미지 ~ 텍스트 간 간격 수정
PR과 관련된 화면을 첨부해주세요.
| <img src="https://github.com/YAPP-Github/Coffice-iOS/assets/4410021/41564e77-4197-4f02-b52c-86463ffef640" width="200"> | <img src="https://github.com/YAPP-Github/Coffice-iOS/assets/4410021/1d43be74-ae8a-415e-8d58-2eb30db2302b" width="200"> |
```
```
close #260
> [Fix] #260 카페상세, 리뷰 작성 상단 UI 이미지 ~ 텍스트 간 간격 수정

- Projects/Coffice/Sources/App/Main/MyPage/EditProfile/EditProfileView.swift
- 디자인 요구에 맞게 닉네임 수정화면 플레이스홀더를 교체했습니다.
close #265
> Fix/#265 닉네임 수정화면 플레이스홀더 변경

- Projects/Coffice/Project.swift
- Projects/Coffice/Sources/App/Main/SavedList/SavedListView.swift
- 북마크 화면 나갈때 onDisappear가 호출 안되고 있었어서 북마크 해제하고 나가도 북마크에서 사라지지 않던 문제를 해결했습니다.
- 현재 프로젝트 버전에 맞게 project.swift 파일 수정하였습니다.
close #263
> Fix/#263 저장탭 이탈시 북마크 delete 안되던 것 수정

- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailHeaderCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/NaverMap/NaverMapCore.swift
- 상세화면 복귀시 북마크가 반영되지 않던 문제를 해결했습니다.
|Before|After
|---|---|
|<video src="https://github.com/YAPP-Github/Coffice-iOS/assets/67148595/627b71d3-9d69-4dc1-9998-ecc3067a3e85"> |<video src="https://github.com/YAPP-Github/Coffice-iOS/assets/67148595/0d810baf-5710-4c26-9a60-85659d86b3ca">|
close #267
> Fix/#267 상세화면에서 메인화면 복귀시 북마크 상태 반영 이슈 해결

- Projects/Coffice/Sources/App/Main/Search/CafeDetail/UserReviewCell.swift
- 리뷰 리스트 최하단의 구분선이 없도록 수정했습니다.
| (스크린샷을 넣어주세요) | <img src="https://github.com/YAPP-Github/Coffice-iOS/assets/4410021/c3f9b02a-0ebd-48eb-8865-fa74111a89e3" width="200">|
```
```
close #288
> [Fix] #288 리뷰 목록의 하단 구분선이 없도록 수정

- Projects/Coffice/Sources/App/Entities/OpeningInformation.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/NaverMap/NaverMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/NaverMap/NaverMapView.swift
- 북마크만 보기 버튼, 시간표시 버튼 재검색시에도 상태 유지하기
- 시간 표시 버튼 탭시 맵 중앙으로 15.5 줌레벨 가지도록 카메라 이동하기
- 영업시간 잘못 표기되고 있던 것 수정
- 맵뷰쪽 로직은 리팩토링이 필요한데 지금 당장 하기엔 무리가 있어 중복되는 코드가 존재합니다.
|맵뷰|상세뷰|
|---|---|
|<video src="https://github.com/YAPP-Github/Coffice-iOS/assets/67148595/e7cc990a-abc0-40a8-b733-ee92d717a9dc">|<video src="https://github.com/YAPP-Github/Coffice-iOS/assets/67148595/023f389f-a2b9-4f54-89d0-2cfe3d027115">|
close #278
> Feature/#278 맵뷰 동작 개선

- Projects/Coffice/Sources/App/Entities/Cafe/CapacityLevel.swift
카페 이모지 임시 이모지에서 카페 이모지로 변경
close #291
> [feat] #291 이모지 변경

- Projects/Coffice/Sources/App/AppCoordinatorCore.swift
- Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/UserDefaultsKeyString.swift
- 최초 로그인 시, 카페 팝업뷰 표출
- 지도뷰 첫 진입시, 강남역 주변 카페 표출
close #301
> [Feat] #301 cafeMapView onBoarding 로직 추가

- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> [Fix] #307 회원탈퇴, 로그아웃 후, 재 로그인 시 상단 필터버튼이 동작하지 않는 문제 수정

- Projects/Coffice/Project.swift
- 앱 버전(-> 1.0.6), 빌드 버전(-> 2.0.4) 업데이트
PR과 관련된 화면을 첨부해주세요.
```
```
close #314
> [Chore] #314 앱 버전(-> 1.0.6), 빌드 버전(-> 2.0.4) 업데이트

- Projects/Coffice/Sources/App/Entities/Cafe/Cafe.swift
- Projects/Coffice/Sources/App/Main/SavedList/SavedListView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailHeaderView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewWriteView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListCell.swift
> [Feat] #319 thumbnail, placeholder image 사양 수정

- Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
- Projects/Coffice/Sources/App/Main/Search/NaverMap/NaverMapView.swift
- Projects/Coffice/Sources/App/ViewModifier/IfModifier.swift
수정 후 동작:
https://github.com/YAPP-Github/Coffice-iOS/assets/31721888/699545bf-5413-48ed-aadd-3e1ab794a22b
> [Fix] #333 - CafeCardView 애니메이션 추가 이후 bottomFloatingButtonView 이 가운데 정도에 위치해있는 버그 디버깅
