YAPP-Github/Coffice-iOS

- Projects/Cafe/Sources/App/AppCoordinatorView.swift
- Projects/Cafe/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Cafe/Sources/App/Main/Search/CafeMapView.swift
- 상단 검색바 UI 구성 및 텍스트 입력 후 검색 로직 구성
- BindingState 사용해서 텍스트필드에 입력되는 텍스트 정보를 실시간으로 searchTextFieldText와 바인딩
- figma 참고에서 필터 메뉴 리스트 이름 수정 및 필터 뷰 수평 스크롤 가능하게 UI 수정
- todo : 필터 메뉴 선택 시 세부 필터 설정 UI 추가 개발 필요, (디자인가이드가 없어서 러프하게 구성했습니다.)
- 검색 화면 상단 여백이 보이는 문제 수정 (navigationBarHidden true)
- keyboard 올라올 시, 하단 탭바, 하단 지도 sheet 화면이 위로 올라가는 문제 수정 (.ignoresSafeArea(.keyboard))
<div>
</div>
```
```
close #32
> #32 검색 메인화면 상단 검색바, 필터뷰 기본 UI 구성

- Projects/Coffice/Project.swift
- Projects/Coffice/Sources/App/Main/SavedList/SavedListScreenCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearchDetailCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearchDetailView.swift
- Projects/Coffice/Sources/App/Main/Search/SearchCoordinatorCore.swift
- Projects/Coffice/Sources/App/Main/Search/SearchCoordinatorView.swift
- 카페 검색결과 상세페이지 파일 추가
- 헤더, 메뉴화면 기본 구조 구성
- 3개의 메뉴 뷰의 높이를 랜덤하게 설정했을때 잘 표출되는지 UI 높이 변동 테스트코드 임시 작성 (화면만 추가하고 진입점이 없으므로, 현 앱에 사이드 이펙트 없음)
- 테스트 방법 : SearchCoordinator의 root를 cafeMap -> cafeSearchDetail로 변경하여 화면 확인 가능
> [UI] #51 카페 검색결과 상세페이지 파일 추가 및 헤더, 메뉴화면 기본 구조 구정

- Projects/Coffice/Sources/App/Extensions/CofficeImages+Extensions.swift
- Projects/Coffice/Sources/App/Main/BubbleMessageCore.swift
- Projects/Coffice/Sources/App/Main/BubbleMessageView.swift
- Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
- Projects/Coffice/Sources/App/Main/MainCoordinatorView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearchDetailCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearchDetailMenuView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearchDetailSubInfoView.swift
- 말풍선 UI 및 상세정보 페이지의 가이드 버튼 탭 시 말풍선 표출 하는 플로우를 구성
- 말풍선 background가 탭바까지 가려야 해서 카페 상세 화면의 이벤트를 MainCoordinator에서 받아서 처리하는 방식으로 구현했습니다. (추후 커스텀 UI로 분리 및 개선을 해야겠습니다.)
<div>
</div>
- 카페 상세화면 > 가이드 버튼(i 모양 버튼) 클릭 후 UI 확인 (현재는 샘플 데이터만 나옵니다.)
```
```
close #51
> [UI] #51 카페 검색결과 상세페이지 말풍선 UI 개발

- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
- 검색바 키워드 입력 시 바인딩 이벤트가 연결되도록 수정
- 바인딩 활용하여 개발 시 확인해야 부분 : 키워드 입력으로 바인딩 이벤트 발생 시, 2번씩 action이 호출되어서 이부분 원래이러는지, 버그인지 확인이 필요합니다.
- 검색 키워드 입력 시 바인딩 이벤트 잘 동작하는지 확인 필요
```
```
close #85
> [Fix] #85 검색바 키워드 입력 시 바인딩 이벤트 실행되지 않는 문제 수정

- Projects/Coffice/Resources/Colors.xcassets/grayScale8.colorset/Contents.json
- Projects/Coffice/Sources/App/Dependencies/BookmarkAPIClient.swift
- Projects/Coffice/Sources/App/Entities/Address.swift
- Projects/Coffice/Sources/App/Entities/Cafe.swift
- Projects/Coffice/Sources/App/Entities/CrowdednessResponse.swift
- Projects/Coffice/Sources/App/Entities/TimeOffset.swift
- Projects/Coffice/Sources/App/Main/SavedList/SavedListCoordinatorCore.swift
- Projects/Coffice/Sources/App/Main/SavedList/SavedListCoordinatorView.swift
- Projects/Coffice/Sources/App/Main/SavedList/SavedListCore.swift
- Projects/Coffice/Sources/App/Main/SavedList/SavedListScreenCore.swift
- Projects/Coffice/Sources/App/Main/SavedList/SavedListView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailCore.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailMenuView.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailSubInfoView.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailView.swift
- Projects/Coffice/Sources/App/Main/Search/SearchCoordinatorCore.swift
- Projects/Coffice/Sources/App/Main/Search/SearchScreenCore.swift
- Projects/Network/Sources/DTOs/Requests/SaveToFolderRequestDTO.swift
- Projects/Network/Sources/DTOs/Responses/SearchPlaceResponseDTO.swift
- color grayscale8에 대한 변경사항 반영완료
- 저장탭 UI 구현
- 저장된 카페 탭시 카페 상세화면으로 이동하는 플로우 제작
- 카페 상세화면으로 이동할때 placeId (cafeId)를 받아 해당 카페를 fetch하는 로직 제작
- 저장된 카페 상세화면 진입 후 뒤로가기 버튼 탭시 popView 되도록 동작 구현
- cafeCell 목록을 ForEach로 순회할때 index가 아닌 해당 위치의 instance 기반으로 사용할 수 있도록 Cafe관련 Entity에 Hashable 채택
- SavedList와 Search의 ScreenCore가 파일명, 위치가 뒤바뀌어 있던 것 수정
- TimeOffset 대신 String으로 openedAt, closedAt 파싱하도록 변경 
~~북마크 해제된 카페 일괄삭제 API는 서버에서 리뷰중이므로 배포 이후에 동작 예정입니다.~~
배포 완료되어 반영 완료했습니다.
close #94
> Feature/#94 bookmark view 제작

- Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewTextView.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewWriteCore.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewWriteView.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/Review/KeyboardPresentationReadable.swift
- iOS 16 이상에서 키보드가 올라왔을때 키보드 위로 텍스트뷰 보이지 않는 문제 수정
- iOS15, 16 모두 동작 확인
- 편집 상태에서 빈 뷰 탭 하는 경우, 키보드 내려가고, 텍스트뷰 원 위치로 이동하도록 수정
<div>
</div>
```
```
close #91
> [Fix] #91 리뷰 작성화면 텍스트 뷰 편집 시 편집 사용성 개선

- Projects/Coffice/Sources/App/Main/MyPage/DevTestView.swift
- 개발자 테스트화면 TextField 바인딩 이벤트 2번씩 발생하는 문제 수정
- textFieldStyle을 plain으로 설정하지 않으면, 바인딩이벤트가 2번씩 발생하는 문제가 있었는데, 리뷰작성화면, 검색화면은 수정했으나, 마저 수정하지 못한 개발자 테스트화면 TextField 의 바인딩이벤트 문제를 수정했습니다.
```
```
close #95
> [Fix] #95 개발자 테스트화면 TextField 바인딩 이벤트 2번씩 발생하는 문제 수정

- Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailView.swift
- 카페검색 상세화면 하단 일부가 잘리는 문제를 수정했습니다.
- safe area bottom inset + 탭바 높이를 padding값으로 설정해서 일부 컨텐츠가 잘리지 않도록 수정
[Issue 페이지](https://github.com/YAPP-Github/Coffice-iOS/issues/106)에 to-be 이미지를 첨부했습니다.
```
```
close #106
> [Fix] #106 카페 검색 상세화면 스크롤영역 하단 일부가 잘리는 현상 수정

- Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterMenusView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
- 앞서 재사용을 위해 분리했던 CafeFilterMenus Reducer를 메인 검색화면에 연결했습니다.
+ 검색 메인화면 상단 헤더뷰 UI를 디자인가이드에 맞게 수정했습니다.
- 검색 메인화면 상단 필터뷰 적용 | 검색 메인화면 상단 헤더뷰 UI 수정
<div>
</div>
<br>
<br>
- 상단 필터버튼 좌우 padding 디자인가이드에 맞게 추가 수정했습니다.
```
```
resolved #37 
related #90 #32
> [Chore] #37 검색 메인화면 상단에 필터뷰 UI, 이벤트 연결

- Projects/Coffice/Sources/App/Main/BubbleMessageCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheet.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetViewState.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailCore.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailSubInfoView.swift
- Projects/Coffice/Sources/App/PreferenceKeys/TabBarSizePreferenceKey.swift
- 각 가이드 버튼을 선택했을때 말풍선에 알맞는 설명문구가 나오도록 하는 기능을 추가했습니다. (검색화면, 카페상세화면)
- 검색 상단 필터뷰 변경 후, 카페 상세 테스트용 진입을 위해 검색 메인화면 좌하단에 테스트 floating 버튼을 추가했습니다. (#116)
<div>
</div>
```
```
close #115 #116
> [Feat] #115 #116 카페상세 테스트용 진입점 수정, 말풍선 가이드 메세지 표출 로직 구성 (#37 PR merge 선행 필요)

- Projects/Coffice/Sources/App/Main/MyPage/EditProfile/EditProfileView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearchView.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailCore.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailHeaderView.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailMenuView.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailSubInfoView.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailView.swift
- Projects/Coffice/Sources/Fonts.swift
- 카페 상세화면 UI 디자인가이드 적용했습니다.
- TODO
- 카페 상세화면 지도뷰 추가
- 카페 상세화면 API 미연동 정보 추가 연동
```
```
close #119
> [UI] #119 카페 상세화면 UI 디자인가이드 적용

- Projects/Coffice/Project.swift
- Projects/Coffice/Sources/App/AppCoordinatorCore.swift
- Projects/Coffice/Sources/App/AppDelegate.swift
- Projects/Coffice/Sources/App/CommonBottomSheet/BottomSheet.swift
- Projects/Coffice/Sources/App/CommonBottomSheet/BottomSheetCore.swift
- Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
- Projects/Coffice/Sources/App/Main/MainCoordinatorView.swift
- Projects/Coffice/Sources/App/Main/MyPage/Coordinator+Screen/MyPageCoordinatorCore.swift
- Projects/Coffice/Sources/App/Main/MyPage/EditProfile/EditProfileCore.swift
- Projects/Coffice/Sources/App/Main/MyPage/EditProfile/EditProfileView.swift
- Projects/Coffice/Sources/App/Main/MyPage/MyPageCore.swift
- Projects/Coffice/Sources/App/Main/MyPage/MyPageView.swift
- Projects/Coffice/Sources/App/Main/SavedList/SavedListView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
- Projects/Coffice/Sources/App/Main/ToastConfiguration.swift
- Projects/Coffice/Sources/App/Main/ToastView.swift
- Projects/Coffice/Sources/App/TabBar/TabBarCore.swift
- Tuist/Dependencies.swift
- custom tab bar 구조를 변경했습니다. (TabView로 변경)
- 공용으로 사용할 BottomSheet를 제작하였습니다.
- PopupView 라이브러리를 활용했습니다.
- 사용방법은 myPage 코드를 참고해주세요.
- 마이페이지 화면전환쪽 불필요한 코드를 삭제하거나 묶음으로써 리팩토링했습니다.
```swift
private var tabBarTouchBlockerView: some View {
Color.white.opacity(0.0001)
.frame(height: 65)
}
```
현재 저희 팀이 사용하는 탭바는 시스템이 기본적으로 만들어주는 탭바 위에
커스텀 탭바를 overlay하는 형식입니다.
shouldShowTabBarView를 통해 커스텀 탭바를 hidden 시키게 되면
그 아래에 있던 시스템 기본 탭바가 노출되어 (보이진 않지만 투명 버튼이 존재)
탭바를 숨기게 되더라도 하단을 탭하면 다른 탭으로 이동하는 버그가 있습니다.
이를 막기 위해 탭바사이즈와 같은 영역을 차지하는 View를 얹어주었습니다.
**이때 clear 색상을 쓰면 탭 이벤트가 아래까지 전달되기에 위와 같은 코드를 작성했습니다.**
**white color를 쓰면 화면전환시 white 영역이 차지하는 공간이 네비게이션 push 이전에 먼저 노출되어 UX를 해치기에 clear에 가까운 색상으로 눈속임을 진행했습니다.**
https://github.com/YAPP-Github/Coffice-iOS/assets/67148595/92868995-62b8-42dd-bb3f-95721d334d7e
close #137
> Feature/#137 커스텀 탭바 구조 수정, 마이페이지 동작연결

- Projects/Coffice/Project.swift
- Projects/Coffice/Sources/App/Main/MainCoordinatorView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterMenusView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/CafeDetailNaverMapView.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailMenuView.swift
- Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailView.swift
- 카페 상세화면에 맵뷰를 추가했습니다.
- 필터 메뉴뷰의 레이아웃을 피그마에 맞게 수정했습니다.
- 커스텀 탭바가 시스템 기본 탭바의 높이보다 16px 높아서 하단 컨텐츠를 가리던 문제를 TabView에 패딩을 주어 해결했습니다.
close #131
> Feature/#131 상세화면 맵뷰 추가

- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailMenuView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewWriteCore.swift
- 카페상세 > 리뷰목록에서 표출되는 수정/삭제/신고 옵션버튼이 있는 팝업 표출 로직을 구성했습니다.
- 자신이 작성한 리뷰는 삭제/수정 옵션이, 자신이 작성한 리뷰가 아니면 신고하기 옵션이 표출됩니다.
- todo
- 리뷰 삭제/신고 기능 구현 예정입니다.
- 카페상세 Reducer가 많이 커서 추후에 Reducer 분리작업을 진행할 생각입니다.
- 리뷰작성화면에서 텍스트 입력 후 에러 로그가 남는 증상이 있어서 수정 예정입니다.
- 리뷰 수정/삭제/신고 팝업 표출 UI, 이벤트 구성 | 리뷰 수정 플로우 구성 (리뷰 수정 API 연동)
<div>
</div>
```
```
related #161 #139
> [Feat] 카페 상세 > 리뷰 목록 관련 팝업 (신고, 수정, 삭제) 표출로직 구성

- Projects/Coffice/Sources/App/Main/MyPage/EditProfile/EditProfileCore.swift
- Projects/Coffice/Sources/App/Main/MyPage/EditProfile/EditProfileView.swift
현재 View에 들어가는 경고문이 2종류여서 enum 타입을 활용하여, 예시용으로  구현하였습니다~!
분기처리는 추후 별도로 필요할 것 같습니다! enum타입은 서버 코드를 참고하였습니다..!
width ="200" >
close #172
> [Feat] #172 nickname UI

- Projects/Coffice/Sources/App/Dependencies/CheckNicknameAPIClient.swift
- Projects/Coffice/Sources/App/Entities/CheckNicknameResponse.swift
- Projects/Network/Sources/CoreNetwork.swift
- Projects/Network/Sources/DTOs/Requests/CheckNicknameRequestDTO.swift
- Projects/Network/Sources/NetworkResult.swift
- CheckNicknameAPIClient 제작
- network result 파싱 구조 변경 예정
- 현재 배포가 코앞이기에 기존 구조는 건드리지 않고 닉네임 검사를 위한 임시 구조 제작하여 사용하였습니다.
close #178
> Feature/#178 닉네임 검사 로직 제작

- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchCore.swift
- 카페 검색 시, "강남역", "강남" 입력 후 연관검색어로 셀을 클릭하거나 엔터를 입력했을 시,
해당 위치로 화면전환이 이루어지지 않는 상황
- 필터 검색 로직이 제거되어, 필터 반영이 이루어지지 않는 상황
- 카페 검색 시, ex) "스타벅스" 입력 후 검색 -> 단일 카페만 화면에 표출되는 상황
- 카페 검색 시, "강남역", "강남" 입력 후 연관검색어로 셀을 클릭하거나 엔터를 입력했을 시,
해당 위치로 화면전환이 이루어지며, 주위 카페목록을 표출
- 필터 검색 로직 추가, 필터 반영
- 카페 검색 시, ex) "스타벅스" 입력 후 검색 -> 조건에 충족하는 카페 화면에 표출
close #183
> [Fix] #183 검색 플로우 수정

- Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
- Projects/Coffice/Sources/App/Main/MainCoordinatorView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheet.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetView.swift
- 필터 바텀 시트 뷰, 카페 상세화면을 통한 말풍선 뷰 표출방식을 수정했습니다. (기존 로직에서 북마크를 통한 카페상세 진입 시 말풍선 뷰 표출이 안되는 문제 존재)
- MainCoordinator의 bubbleMssage 관련 코드 제거 후 PopupView 라이브러리 적용
- todo:
- 말풍선 뷰 표출 시, 하단 safe area에 흰색 패딩이 남아있는 문제가 있어서 원인 확인 및 수정 예정입니다. 
```
```
close #181
> [Refactor] 필터 바텀 시트 뷰, 카페 상세화면을 통한 말풍선 뷰 표출방식 수정

- Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
- Projects/Coffice/Sources/App/Main/MainCoordinatorView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheet.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterMenusCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterMenusView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListCore.swift
- 필터 bottom sheet 표출 및 필터 설정 로직을 개선했습니다.
- MainCoordinator의 필터 설정 관련 로직 제거, 실제 표출하는 화면에서 관련 BindingState를 관리
- PopupView library 적용
PR과 관련된 화면을 첨부해주세요.
- bottom sheet을 통한 필터 설정 정상 동작 여부 확인
- bottom sheet을 통한 말풍선 뷰 표출 로직 정상 동작 확인
- 상단 필터 설정 뷰가 있는 화면 간 필터 설정 데이터 연동 여부 확인
```
```
close #190
> Feature/#190 필터 bottom sheet 표출 및 필터 설정 로직 개선 (PopupView Library 적용)

- Projects/Coffice/Sources/App/CommonComponents/CommonBottomSheet/BottomSheet.swift
- Projects/Coffice/Sources/App/Login/LoginCore.swift
- Projects/Coffice/Sources/App/Login/LoginServiceTermsBottomSheetView.swift
- Projects/Coffice/Sources/App/Login/LoginServiceTermsSheetCore.swift
- Projects/Coffice/Sources/App/Login/LoginView.swift
- 로그인 이용약관 바텀 시트뷰 UI를 구성 후, 로그인 flow와 연결했습니다.
- 실기기에서 약관 동의 후 카카오, 애플로그인 flow 정상 동작 확인했습니다.
- todo
- 이용약관 시트에서 약관동의 웹뷰 표출로직 구현이 필요합니다.
- 예시 영상, 시뮬레이터 기준 영상이라 약관 동의 이후 실제 로그인 플로우는 나오지 않습니다. (시뮬에서 애플로그인은 약관동의 표출로직도 못감)
- 테스트 하신다면, 실기기로 확인 부탁드립니다. 🙏🏻
- 약관 동의 후 카카오, 애플로그인 flow가 동작 여부 확인
- 애플로그인은 약관 동의 바텀 시트뷰 표출 전 일부 로그인 관련 플로우가 존재, 이후 바텀 시트뷰가 표출 됨
```
```
related #193
> Feature/#193 login terms bottom sheet (#197 merge 선행 필요)

- Projects/Coffice/Resources/Colors.xcassets/grayScale1.colorset/Contents.json
- Projects/Coffice/Resources/Colors.xcassets/grayScale10.colorset/Contents.json
- Projects/Coffice/Resources/Colors.xcassets/grayScale2.colorset/Contents.json
- Projects/Coffice/Resources/Colors.xcassets/grayScale3.colorset/Contents.json
- Projects/Coffice/Resources/Colors.xcassets/grayScale4.colorset/Contents.json
- Projects/Coffice/Resources/Colors.xcassets/grayScale5.colorset/Contents.json
- Projects/Coffice/Resources/Colors.xcassets/grayScale6.colorset/Contents.json
- Projects/Coffice/Resources/Colors.xcassets/grayScale7.colorset/Contents.json
- Projects/Coffice/Resources/Colors.xcassets/grayScale8.colorset/Contents.json
- Projects/Coffice/Resources/Colors.xcassets/grayScale9.colorset/Contents.json
- Projects/Coffice/Resources/Colors.xcassets/kakao.colorset/Contents.json
- Projects/Coffice/Resources/Colors.xcassets/red.colorset/Contents.json
- Projects/Coffice/Resources/Colors.xcassets/secondary0.colorset/Contents.json
- Projects/Coffice/Resources/Colors.xcassets/secondary1.colorset/Contents.json
- Projects/Coffice/Resources/Colors.xcassets/secondary2.colorset/Contents.json
- Projects/Coffice/Resources/Colors.xcassets/secondary3.colorset/Contents.json
Color Asset universal로 수정 ipad 뷰 깨짐 현상 해결
|<img src="https://github.com/YAPP-Github/Coffice-iOS/assets/108966759/e7a4d82b-223d-4921-b143-6dd13f551afe" width="200"> |  <img src="https://github.com/YAPP-Github/Coffice-iOS/assets/108966759/c3d53761-aa77-43c6-a348-aee38a373329" width="200">|
close #205
> [Fix] Color Asset IPhone -> universal로 수정

- Projects/Coffice/Sources/App/Entities/ResponseValue/GetReviewResponse.swift
- Projects/Coffice/Sources/App/Extensions/String+Extensions.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailSubInfoView.swift
- 아래 영상에서 리뷰작성 시간정보도 정확한 시간 정보가 나옴을 설명하기 위해 임의로 dateFormat을 시/분/초가 함께 나오게 했습니다. (PR에는 올리지 않았어요)
```
```
related #186 
close #221
> [Feat] #221 #186 카페 상세 시간/푸드/음료 정보 표시방식 수정 (#213 선행 merge 필요)

- Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchView.swift
최근 검색어, 검색어 목록의 여백 부분이 터치영역으로 적용되지 않는 문제
- 최근 검색어 목록 터치 영역을 수정하였습니다
- 검색 키워드 입력 시, 표출되는 역(강남역..), 카페 터치 영역을 수정하였습니다.
close #220
> [Fix] #220 최근 검색어 목록 및 검색키워드 입력 시, 표출되는 지하철, 카페 셀 터치 영역 수정

- Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchView.swift
- 검색어 입력 시, 표출되는 지하철 역 목록과 카페 목록 사이의 회색 가로선 부재
- 텍스트 필드에 쓰여진 텍스트 타이포가 다름. (subtitle_md)
close #236
> [Feat]/#236 검색어 입력 시, 표출되는 지하철 역 목록과 카페 목록 사이의 회색 가로선 부재(+ 검색 텍스트 필드 폰트 수정)

- Projects/Coffice/Sources/App/Extensions/UINavigationController+Extensions.swift
해당 pr에서 작업한 내역을 적어주세요.
- 네비게이션 전환 후, 이전 화면으로 복귀하기 위해 좌측 swipe 시 pop이 되지 않았던 문제를 수정합니다.
- 뒤로가기 버튼과 동일하게 swipe를 통한 화면 pop 시에도 route 정상적으로 pop 되는 것 확인
- [reference](https://stackoverflow.com/questions/59234958/swiftui-navigationbarbackbuttonhidden-swipe-back-gesture/60067845#60067845)
```
```
close #238
> [Fix] #238 네비게이션 전환 후, 좌측 swipe 시 pop이 되지 않는 문제 수정

- Projects/Coffice/Sources/App/Entities/Cafe/CafeGroupSeatLevel.swift
- Projects/Coffice/Sources/App/Entities/Cafe/CapacityLevel.swift
- Projects/Coffice/Sources/App/Entities/Cafe/ElectricOutletLevel.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailSubInfoView.swift
- 카페 상세화면 디자이너 요청사항을 반영했습니다.
- 이미지는 하단 라벨의 trailing에 정렬되도록 하고, cell간 간격을 40으로 맞춰달라는 요구사항 반영
close #243
> [Feat] #243 디자인 QA 요청 사항 반영

- Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetViewState.swift
해당 pr에서 작업한 내역을 적어주세요.
- 영업시간 하단 시트 필터에서 영업시간보기 필터 버튼을 제거했습니다. (floating button으로 변경되어서 불필요해짐)
```
```
close #250
> [Fix] #250 영업시간 하단 시트 필터에서 영업시간보기 필터 버튼 제거

- Projects/Coffice/Sources/App/CommonComponents/CommonBottomSheet/BottomSheet.swift
- QA팀 요청에 따라 바텀시트 표출/숨김 애니메이션 속도를 수정했습니다.
- PopupView library의 기본 애니메이션 속도는 0.3초인데, 0.2초로 변경했습니다.
```
```
close #252
> [Fix] #252 바텀시트 표출/숨김 애니메이션 속도 수정 (easeOut 0.3 -> 0.2 seconds)

- Projects/Coffice/Project.swift
- Projects/Coffice/Sources/App/Entities/User.swift
- Projects/Coffice/Sources/App/Main/MyPage/MyPageView.swift
- 익명 유저가 OAuth 로그인 한 경우 서버에는 사용자의 loginTypes로 ANONYMOUS와 KAKAO를 둘 다 담아서 보내줍니다.
- 기존 로직에서는 loginTypes중 가장 첫번째 값을 사용했지만, 이때 익명이 첫번째 값에 포함되어있는 경우 익명 사용자로 취급되었었기에 이를 수정했습니다.
close #270
> Feature/#270 로그인 타입 여러개인경우 소셜 로그인 상태가 먼저 노출되도록 변경

- Projects/Coffice/Sources/App/Login/LoginServiceTermsBottomSheetView.swift
- 약관동의 하단 시트의 "약관 전체 동의" 영역이 아이콘 뿐만아니라 리스트 셀 전체가 터치영역이 되도록 수정했습니다.
```
```
close #280
> [Fix] #280 약관동의 하단 시트 아이콘 뿐만아니라 리스트 셀 전체가 터치영역 이어야함

- Projects/Coffice/Sources/App/CommonComponents/BubbleMessage/BubbleMessageView.swift
- Projects/Coffice/Sources/App/Main/MyPage/DevTest/DevTestCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailMenuCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheet.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeFilterMenusCore.swift
- #282 필터 바텀시트 초기화 사양 수정
| (스크린샷을 넣어주세요) | <img src="https://github.com/YAPP-Github/Coffice-iOS/assets/4410021/2d6b5b65-16e9-4863-96ec-2588f51ea552" width="200"> |
- #283 설명 메세지뷰 하단 흰띠 보이는 문제 수정
| (스크린샷을 넣어주세요) | <img src="https://github.com/YAPP-Github/Coffice-iOS/assets/4410021/327d71ea-b394-40c0-a250-4940fe588e1f" width="200"> |
#280 #283 
```
```
close #282 #283
> [Fix] #282, #283 필터 바텀시트 초기화 사양, 설명 메세지뷰 하단 흰띠 보이는 문제 수정

- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailMenuCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewOptionButtonsCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/UserReviewCell.swift
- 기존에는 리뷰 태그에 긍적적인 내용만 보이고 있었습니다.
- 긍정적인 내용 이외의 내용 ex) ‘콘센트가 적어요’ 같은 값도 보이도록 수정했습니다.
```
```
close #285
> [Feat] #285 카페 상세의 리뷰 태그, 긍정적인 내용 이외의 ‘콘센트가 적어요’ 같은 값도 보이도록 수정

- Projects/Coffice/Sources/App/Main/SavedList/SavedListCore.swift
- Projects/Coffice/Sources/App/Main/SavedList/SavedListView.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailMenuCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailView.swift
- 카페상세, 저장리스트 refresh control알 적용했습니다.
- refreshable viewModifier를 사용하는 방식으로 적용했는데, iOS16 이상에서 기능이 동작하고 있습니다. (시뮬레이터 iOS15에서는 pull to refresh 동작이 안됨) 
- refreshable block에 메인스레드 관련 에러 로그가 남아서 MainActor를 적용했습니다.
```
```
close #297
> [Feat] #297 카페상세, 저장리스트 refresh control 적용

- Projects/Coffice/Sources/App/Main/SavedList/SavedListView.swift
> [Fix] #323 저장리스트 목록이 스크롤 가능할 정도로 많을 경우 하단 정보가 잘려보이는 현상 수정

- Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
- Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
- 마커 클릭시에 bottom의 cardview 애니메이션 추가
-  offset 과 opacity 동시에 적용
> [Feature] 마커 클릭시 bottom의 cardview 애니메이션 추가

- Projects/Coffice/Sources/App/Main/MyPage/MyPageView.swift
- VStack으로 적용되어있어 버튼이 많아지거나 작은 화면에서 하단의 버튼이 TabBar에 가려짐
버튼에 ScrollView 적용
https://github.com/YAPP-Github/Coffice-iOS/assets/31721888/b774511b-f06b-4b16-93ca-20c444663524
close #335
> [Fix, 스크롤뷰를 적용하지않아 작은화면에서 버튼이 가려지는 이슈 디버깅]
